title: "Buttons"
description: |
  Buttons are used for definite action such as selecting an option, confirming pick up or agree to pickup. They can be links to different pages or simply confirmations.

patterns:
  basic:
    title: "Basic"
    description: |
        This button is used through the app to select an option.
