title: "Buttons"
description: |
  Buttons are used for definite action such as selecting an option, confirming pick up or agree to pickup. They can be links to different pages or simply confirmations.

patterns:
  basic:
    title: "Basic"
    description: |
        This button is used through the app to select an option.
  ghost:
    title: "Ghost"
    description: |
      This button is used for banners to match styles.
  light:
    title: "Light"
    description: |
      This is the most dramatic, used for buying and checking out.
