title: "Header"
description: |
  The navigation bar on every page

patterns:
  nav:
    title: "Navigation"
    description: |
      This form field will be used for users to type in their location so they can search within their area.
