title: "Notfications"
description: |
  All the possible notifications that could display while using the application.

patterns:
  notification:
    title: "Post Notification"
    description: |
      The notifcation that will display when a user posts a new item.
